<?php

namespace Database\Seeders;

use App\Models\Tryout;
use App\Models\TryoutQuestion;
use Illuminate\Database\Seeder;

class TryoutSeeder extends Seeder
{
    public function run(): void
    {
        // Buat Try Out
        $tryout = Tryout::create([
            'name' => 'Try Out CPNS 2024 - Paket 1',
            'description' => 'Simulasi ujian CPNS lengkap dengan 110 soal (30 TWK + 35 TIU + 45 TKP). Durasi 100 menit.',
            'duration' => 100,
            'total_questions_twk' => 30,
            'total_questions_tiu' => 35,
            'total_questions_tkp' => 45,
            'total_questions' => 110,
            'status' => 'active',
            'created_by' => 1,
        ]);

        $order = 0;

        // ==================== TWK (30 SOAL) ====================
        $twkQuestions = [
            [
                'question' => 'Pancasila sebagai dasar negara Indonesia disahkan pada tanggal...',
                'a' => '1 Juni 1945', 'b' => '17 Agustus 1945', 'c' => '18 Agustus 1945',
                'd' => '22 Juni 1945', 'e' => '17 Juli 1945',
                'answer' => 'c',
                'explanation' => 'Pancasila disahkan sebagai dasar negara pada 18 Agustus 1945 melalui sidang PPKI.',
            ],
            [
                'question' => 'Sila pertama Pancasila adalah...',
                'a' => 'Kemanusiaan yang adil dan beradab',
                'b' => 'Persatuan Indonesia',
                'c' => 'Kerakyatan yang dipimpin oleh hikmat kebijaksanaan',
                'd' => 'Ketuhanan Yang Maha Esa',
                'e' => 'Keadilan sosial bagi seluruh rakyat Indonesia',
                'answer' => 'd',
                'explanation' => 'Sila pertama Pancasila adalah Ketuhanan Yang Maha Esa yang menunjukkan bangsa Indonesia adalah bangsa yang religius.',
            ],
            [
                'question' => 'Bhinneka Tunggal Ika berasal dari kitab...',
                'a' => 'Arjunawiwaha', 'b' => 'Sutasoma',
                'c' => 'Negarakertagama', 'd' => 'Pararaton',
                'e' => 'Ramayana',
                'answer' => 'b',
                'explanation' => 'Bhinneka Tunggal Ika berasal dari kitab Sutasoma karya Mpu Tantular pada zaman Kerajaan Majapahit.',
            ],
            [
                'question' => 'Pembukaan UUD 1945 terdiri dari... alinea',
                'a' => '2', 'b' => '3', 'c' => '4', 'd' => '5', 'e' => '6',
                'answer' => 'c',
                'explanation' => 'Pembukaan UUD 1945 terdiri dari 4 alinea yang memuat cita-cita dan dasar negara.',
            ],
            [
                'question' => 'Bentuk negara Indonesia adalah...',
                'a' => 'Serikat', 'b' => 'Kesatuan', 'c' => 'Federal',
                'd' => 'Konfederasi', 'e' => 'Persemakmuran',
                'answer' => 'b',
                'explanation' => 'Indonesia adalah negara kesatuan berbentuk republik sebagaimana tercantum dalam Pasal 1 ayat (1) UUD 1945.',
            ],
            [
                'question' => 'Lagu kebangsaan Indonesia adalah...',
                'a' => 'Rayuan Pulau Kelapa', 'b' => 'Indonesia Raya',
                'c' => 'Garuda Pancasila', 'd' => 'Halo-halo Bandung',
                'e' => 'Tanah Airku',
                'answer' => 'b',
                'explanation' => 'Indonesia Raya adalah lagu kebangsaan Indonesia yang diciptakan oleh WR Soepratman.',
            ],
            [
                'question' => 'Hari Kesaktian Pancasila diperingati setiap tanggal...',
                'a' => '1 Juni', 'b' => '18 Agustus', 'c' => '1 Oktober',
                'd' => '28 Oktober', 'e' => '10 November',
                'answer' => 'c',
                'explanation' => 'Hari Kesaktian Pancasila diperingati setiap 1 Oktober untuk memperingati peristiwa G30S/PKI.',
            ],
            [
                'question' => 'Sistem pemerintahan Indonesia adalah...',
                'a' => 'Parlementer', 'b' => 'Presidensial',
                'c' => 'Semipresidensial', 'd' => 'Monarki',
                'e' => 'Federal',
                'answer' => 'b',
                'explanation' => 'Indonesia menganut sistem pemerintahan presidensial di mana presiden adalah kepala negara sekaligus kepala pemerintahan.',
            ],
            [
                'question' => 'Undang-Undang Dasar 1945 telah diamandemen sebanyak... kali',
                'a' => '2', 'b' => '3', 'c' => '4', 'd' => '5', 'e' => '6',
                'answer' => 'c',
                'explanation' => 'UUD 1945 telah diamandemen 4 kali yaitu tahun 1999, 2000, 2001, dan 2002.',
            ],
            [
                'question' => 'Tokoh yang dikenal sebagai Bapak Proklamator adalah...',
                'a' => 'Ir. Soekarno dan Drs. Moh. Hatta',
                'b' => 'Ir. Soekarno dan Jenderal Soedirman',
                'c' => 'Moh. Hatta dan Sutan Syahrir',
                'd' => 'Ir. Soekarno dan Ki Hajar Dewantara',
                'e' => 'Bung Tomo dan Ir. Soekarno',
                'answer' => 'a',
                'explanation' => 'Ir. Soekarno dan Drs. Moh. Hatta adalah proklamator kemerdekaan Indonesia yang membacakan teks proklamasi pada 17 Agustus 1945.',
            ],
            [
                'question' => 'Semboyan pendidikan yang dicetuskan Ki Hajar Dewantara adalah...',
                'a' => 'Tut Wuri Handayani',
                'b' => 'Ing Ngarsa Sung Tulada, Ing Madya Mangun Karsa, Tut Wuri Handayani',
                'c' => 'Bersatu kita teguh, bercerai kita runtuh',
                'd' => 'Merdeka atau mati',
                'e' => 'Satu nusa satu bangsa',
                'answer' => 'b',
                'explanation' => 'Ki Hajar Dewantara mencetuskan semboyan Ing Ngarsa Sung Tulada (di depan memberi teladan), Ing Madya Mangun Karsa (di tengah membangun kemauan), Tut Wuri Handayani (dari belakang memberi dorongan).',
            ],
            [
                'question' => 'Bendera Indonesia disebut Sang Saka Merah Putih yang pertama kali dikibarkan pada...',
                'a' => '17 Agustus 1945', 'b' => '28 Oktober 1928',
                'c' => '1 Juni 1945', 'd' => '18 Agustus 1945',
                'e' => '20 Mei 1908',
                'answer' => 'a',
                'explanation' => 'Sang Saka Merah Putih pertama kali dikibarkan pada hari proklamasi kemerdekaan 17 Agustus 1945 di Jalan Pegangsaan Timur 56.',
            ],
            [
                'question' => 'Kepanjangan dari NKRI adalah...',
                'a' => 'Negara Kesatuan Republik Indonesia',
                'b' => 'Negara Kebangsaan Republik Indonesia',
                'c' => 'Nusa dan Karya Rakyat Indonesia',
                'd' => 'Negara Kesatuan Rakyat Indonesia',
                'e' => 'Negara Kesejahteraan Republik Indonesia',
                'answer' => 'a',
                'explanation' => 'NKRI adalah Negara Kesatuan Republik Indonesia, bentuk negara yang tidak terbagi-bagi dalam negara bagian.',
            ],
            [
                'question' => 'Hari Kebangkitan Nasional diperingati setiap tanggal...',
                'a' => '17 Agustus', 'b' => '28 Oktober', 'c' => '20 Mei',
                'd' => '1 Oktober', 'e' => '10 November',
                'answer' => 'c',
                'explanation' => 'Hari Kebangkitan Nasional diperingati setiap 20 Mei, bertepatan dengan berdirinya organisasi Budi Utomo pada tahun 1908.',
            ],
            [
                'question' => 'Organisasi pertama yang menjadi cikal bakal pergerakan nasional adalah...',
                'a' => 'Indische Partij', 'b' => 'Budi Utomo',
                'c' => 'Sarekat Islam', 'd' => 'Muhammadiyah',
                'e' => 'Perhimpunan Indonesia',
                'answer' => 'b',
                'explanation' => 'Budi Utomo didirikan pada 20 Mei 1908 oleh Dr. Soetomo dan menjadi organisasi pergerakan nasional pertama di Indonesia.',
            ],
            [
                'question' => 'Pasal dalam UUD 1945 yang mengatur tentang hak asasi manusia adalah...',
                'a' => 'Pasal 27-34', 'b' => 'Pasal 28A-28J',
                'c' => 'Pasal 24-30', 'd' => 'Pasal 1-5',
                'e' => 'Pasal 31-37',
                'answer' => 'b',
                'explanation' => 'Pasal 28A sampai 28J UUD 1945 mengatur secara khusus tentang Hak Asasi Manusia.',
            ],
            [
                'question' => 'Lembaga negara yang berwenang mengubah dan menetapkan UUD adalah...',
                'a' => 'DPR', 'b' => 'DPD', 'c' => 'MPR',
                'd' => 'MK', 'e' => 'MA',
                'answer' => 'c',
                'explanation' => 'MPR (Majelis Permusyawaratan Rakyat) berwenang mengubah dan menetapkan UUD sesuai Pasal 3 UUD 1945.',
            ],
            [
                'question' => 'Arti dari Bhinneka Tunggal Ika adalah...',
                'a' => 'Satu nusa satu bangsa',
                'b' => 'Berbeda-beda tetapi tetap satu',
                'c' => 'Bersatu dalam perbedaan',
                'd' => 'Indonesia bersatu',
                'e' => 'Persatuan dan kesatuan',
                'answer' => 'b',
                'explanation' => 'Bhinneka Tunggal Ika berasal dari bahasa Jawa Kuno yang berarti berbeda-beda tetapi tetap satu.',
            ],
            [
                'question' => 'Nasionalisme adalah paham yang mengutamakan...',
                'a' => 'Kepentingan pribadi',
                'b' => 'Kepentingan golongan',
                'c' => 'Kepentingan bangsa sendiri',
                'd' => 'Kepentingan internasional',
                'e' => 'Kepentingan daerah',
                'answer' => 'c',
                'explanation' => 'Nasionalisme adalah paham yang menempatkan kepentingan bangsa di atas kepentingan individu atau golongan.',
            ],
            [
                'question' => 'Sumpah Pemuda dicetuskan pada tahun...',
                'a' => '1908', 'b' => '1928', 'c' => '1945',
                'd' => '1950', 'e' => '1966',
                'answer' => 'b',
                'explanation' => 'Sumpah Pemuda dicetuskan pada 28 Oktober 1928 dalam Kongres Pemuda II.',
            ],
            [
                'question' => 'Dasar hukum pembentukan Mahkamah Konstitusi adalah...',
                'a' => 'UUD 1945 Pasal 24C',
                'b' => 'UUD 1945 Pasal 24A',
                'c' => 'UUD 1945 Pasal 25',
                'd' => 'UUD 1945 Pasal 20',
                'e' => 'UUD 1945 Pasal 22',
                'answer' => 'a',
                'explanation' => 'Mahkamah Konstitusi dibentuk berdasarkan UUD 1945 Pasal 24C yang berwenang mengadili pada tingkat pertama dan terakhir.',
            ],
            [
                'question' => 'Tokoh yang mencetuskan konsep Trisakti adalah...',
                'a' => 'Moh. Hatta', 'b' => 'Ir. Soekarno',
                'c' => 'Soeharto', 'd' => 'B.J. Habibie',
                'e' => 'Mohammad Natsir',
                'answer' => 'b',
                'explanation' => 'Ir. Soekarno mencetuskan konsep Trisakti: berdaulat di bidang politik, berdikari di bidang ekonomi, berkepribadian di bidang kebudayaan.',
            ],
            [
                'question' => 'Hari Pahlawan diperingati setiap tanggal...',
                'a' => '17 Agustus', 'b' => '28 Oktober', 'c' => '10 November',
                'd' => '1 Juni', 'e' => '20 Mei',
                'answer' => 'c',
                'explanation' => 'Hari Pahlawan diperingati setiap 10 November untuk mengenang pertempuran Surabaya tahun 1945.',
            ],
            [
                'question' => 'Pancasila berfungsi sebagai...',
                'a' => 'Dasar negara', 'b' => 'Undang-undang',
                'c' => 'Peraturan pemerintah', 'd' => 'Hukum adat',
                'e' => 'Konvensi',
                'answer' => 'a',
                'explanation' => 'Pancasila berfungsi sebagai dasar negara dan pandangan hidup bangsa Indonesia.',
            ],
            [
                'question' => 'Pertempuran Ambarawa dipimpin oleh...',
                'a' => 'Jenderal Soedirman', 'b' => 'Letkol Isdiman',
                'c' => 'Bung Tomo', 'd' => 'Sultan Hamengku Buwono IX',
                'e' => 'Kolonel Soeharto',
                'answer' => 'b',
                'explanation' => 'Pertempuran Ambarawa dipimpin oleh Letkol Isdiman yang gugur dan kemudian digantikan oleh Kolonel Soedirman.',
            ],
            [
                'question' => 'Berdasarkan UUD 1945, Presiden Indonesia dipilih oleh...',
                'a' => 'MPR', 'b' => 'DPR', 'c' => 'Rakyat secara langsung',
                'd' => 'DPD', 'e' => 'Partai politik',
                'answer' => 'c',
                'explanation' => 'Berdasarkan Pasal 6A UUD 1945 hasil amandemen, presiden dan wakil presiden dipilih langsung oleh rakyat.',
            ],
            [
                'question' => 'Sistem ketatanegaraan Indonesia menganut prinsip...',
                'a' => 'Sentralisasi', 'b' => 'Desentralisasi',
                'c' => 'Dekonsentrasi', 'd' => 'Tugas pembantuan',
                'e' => 'Otonomi daerah',
                'answer' => 'e',
                'explanation' => 'Indonesia menganut prinsip otonomi daerah yang luas dalam kerangka NKRI.',
            ],
            [
                'question' => 'Kewajiban warga negara membayar pajak diatur dalam UUD 1945 Pasal...',
                'a' => '23', 'b' => '23A', 'c' => '23B', 'd' => '23C', 'e' => '23D',
                'answer' => 'b',
                'explanation' => 'Pasal 23A UUD 1945 menyatakan bahwa pajak dan pungutan lain yang bersifat memaksa untuk keperluan negara diatur dengan undang-undang.',
            ],
            [
                'question' => 'Makna sila Kerakyatan yang Dipimpin oleh Hikmat Kebijaksanaan dalam Permusyawaratan/Perwakilan adalah...',
                'a' => 'Kekuasaan di tangan rakyat dan dilaksanakan melalui musyawarah',
                'b' => 'Kekuasaan di tangan presiden',
                'c' => 'Kekuasaan di tangan MPR',
                'd' => 'Kekuasaan di tangan partai politik',
                'e' => 'Kekuasaan di tangan golongan mayoritas',
                'answer' => 'a',
                'explanation' => 'Sila keempat bermakna bahwa kedaulatan berada di tangan rakyat dan dilaksanakan melalui mekanisme musyawarah untuk mufakat.',
            ],
            [
                'question' => 'Tokoh yang memimpin delegasi Indonesia dalam Konferensi Meja Bundar adalah...',
                'a' => 'Ir. Soekarno', 'b' => 'Moh. Hatta',
                'c' => 'Sutan Syahrir', 'd' => 'Amir Sjarifuddin',
                'e' => 'Agus Salim',
                'answer' => 'b',
                'explanation' => 'Moh. Hatta memimpin delegasi Indonesia dalam Konferensi Meja Bundar (KMB) di Den Haag, Belanda pada tahun 1949.',
            ],
        ];

        foreach ($twkQuestions as $q) {
            $order++;
            TryoutQuestion::create([
                'tryout_id' => $tryout->id,
                'order_number' => $order,
                'category' => 'twk',
                'question_text' => $q['question'],
                'option_a' => $q['a'], 'option_b' => $q['b'],
                'option_c' => $q['c'], 'option_d' => $q['d'],
                'option_e' => $q['e'],
                'correct_answer' => $q['answer'],
                'explanation' => $q['explanation'],
            ]);
        }

        // ==================== TIU (35 SOAL) ====================
        $tiuQuestions = [
            [
                'question' => 'Sinonim dari kata "Kompeten" adalah...',
                'a' => 'Mampu', 'b' => 'Lemah', 'c' => 'Bodoh',
                'd' => 'Cerdas', 'e' => 'Pintar',
                'answer' => 'a',
                'explanation' => 'Kompeten berarti mampu atau cakap dalam melakukan sesuatu.',
            ],
            [
                'question' => 'Antonim dari kata "Mayoritas" adalah...',
                'a' => 'Minoritas', 'b' => 'Sebagian', 'c' => 'Seluruh',
                'd' => 'Banyak', 'e' => 'Rata-rata',
                'answer' => 'a',
                'explanation' => 'Mayoritas berarti sebagian besar, antonimnya adalah minoritas (sebagian kecil).',
            ],
            [
                'question' => '2, 4, 6, 8, 10, ... Angka selanjutnya adalah...',
                'a' => '11', 'b' => '12', 'c' => '13', 'd' => '14', 'e' => '15',
                'answer' => 'b',
                'explanation' => 'Pola deret adalah penambahan 2 setiap langkah, sehingga 10 + 2 = 12.',
            ],
            [
                'question' => 'Jika 3 apel harganya Rp15.000, maka harga 5 apel adalah...',
                'a' => 'Rp20.000', 'b' => 'Rp25.000', 'c' => 'Rp30.000',
                'd' => 'Rp35.000', 'e' => 'Rp40.000',
                'answer' => 'b',
                'explanation' => 'Harga per apel = 15.000/3 = Rp5.000. Maka 5 apel = 5 x Rp5.000 = Rp25.000.',
            ],
            [
                'question' => 'Sinonim dari kata "Kontradiksi" adalah...',
                'a' => 'Persamaan', 'b' => 'Pertentangan', 'c' => 'Perbedaan',
                'd' => 'Keselarasan', 'e' => 'Kecocokan',
                'answer' => 'b',
                'explanation' => 'Kontradiksi berarti pertentangan atau hal yang saling bertolak belakang.',
            ],
            [
                'question' => 'Kaki : Sepatu = Tangan : ...',
                'a' => 'Sarung Tangan', 'b' => 'Baju', 'c' => 'Celana',
                'd' => 'Topi', 'e' => 'Kacamata',
                'answer' => 'a',
                'explanation' => 'Sepatu dipakai di kaki, analoginya sarung tangan dipakai di tangan.',
            ],
            [
                'question' => '1, 3, 5, 7, 9, ... Angka selanjutnya adalah...',
                'a' => '10', 'b' => '11', 'c' => '12', 'd' => '13', 'e' => '14',
                'answer' => 'b',
                'explanation' => 'Pola deret adalah bilangan ganjil, setelah 9 adalah 11.',
            ],
            [
                'question' => 'Antonim dari kata "Modern" adalah...',
                'a' => 'Baru', 'b' => 'Canggih', 'c' => 'Kuno',
                'd' => 'Maju', 'e' => 'Mutakhir',
                'answer' => 'c',
                'explanation' => 'Modern berarti terbaru, antonimnya adalah kuno (lama/usang).',
            ],
            [
                'question' => 'Sinonim dari kata "Adaptasi" adalah...',
                'a' => 'Perubahan', 'b' => 'Penyesuaian', 'c' => 'Perbaikan',
                'd' => 'Pengembangan', 'e' => 'Pembaruan',
                'answer' => 'b',
                'explanation' => 'Adaptasi berarti penyesuaian diri terhadap lingkungan atau keadaan baru.',
            ],
            [
                'question' => '3, 6, 12, 24, ... Angka selanjutnya adalah...',
                'a' => '30', 'b' => '36', 'c' => '40', 'd' => '48', 'e' => '50',
                'answer' => 'd',
                'explanation' => 'Pola deret adalah perkalian 2 setiap langkah, sehingga 24 x 2 = 48.',
            ],
            [
                'question' => 'Seorang peternak memiliki 120 ekor ayam. Jika 15% diantaranya adalah ayam jantan, berapa jumlah ayam betina?',
                'a' => '90', 'b' => '96', 'c' => '100', 'd' => '102', 'e' => '108',
                'answer' => 'd',
                'explanation' => 'Ayam jantan = 15% x 120 = 18 ekor. Ayam betina = 120 - 18 = 102 ekor.',
            ],
            [
                'question' => 'Sinonim dari kata "Inovatif" adalah...',
                'a' => 'Kreatif', 'b' => 'Konvensional', 'c' => 'Tradisional',
                'd' => 'Rutin', 'e' => 'Biasa',
                'answer' => 'a',
                'explanation' => 'Inovatif berarti memiliki sifat pembaruan atau kreasi baru, sinonimnya adalah kreatif.',
            ],
            [
                'question' => 'Semua mahasiswa adalah lulusan SMA. Sebagian mahasiswa adalah pekerja paruh waktu. Simpulan yang tepat adalah...',
                'a' => 'Semua pekerja paruh waktu adalah lulusan SMA',
                'b' => 'Sebagian pekerja paruh waktu adalah lulusan SMA',
                'c' => 'Semua lulusan SMA adalah mahasiswa',
                'd' => 'Sebagian lulusan SMA adalah pekerja paruh waktu',
                'e' => 'Tidak ada kesimpulan yang tepat',
                'answer' => 'b',
                'explanation' => 'Karena semua mahasiswa adalah lulusan SMA dan sebagian mahasiswa adalah pekerja paruh waktu, maka sebagian pekerja paruh waktu adalah lulusan SMA.',
            ],
            [
                'question' => 'Antonim dari kata "Konkret" adalah...',
                'a' => 'Nyata', 'b' => 'Abstrak', 'c' => 'Jelas',
                'd' => 'Tepat', 'e' => 'Rill',
                'answer' => 'b',
                'explanation' => 'Konkret berarti nyata atau berwujud, antonimnya adalah abstrak (tidak berwujud).',
            ],
            [
                'question' => '5, 10, 20, 40, 80, ... Angka selanjutnya adalah...',
                'a' => '100', 'b' => '120', 'c' => '140', 'd' => '160', 'e' => '180',
                'answer' => 'd',
                'explanation' => 'Pola deret adalah perkalian 2, sehingga 80 x 2 = 160.',
            ],
            [
                'question' => 'Sinonim dari kata "Edukasi" adalah...',
                'a' => 'Hiburan', 'b' => 'Pendidikan', 'c' => 'Pelatihan',
                'd' => 'Pengajaran', 'e' => 'Pembelajaran',
                'answer' => 'b',
                'explanation' => 'Edukasi berarti pendidikan, yaitu proses belajar mengajar.',
            ],
            [
                'question' => 'Mobil : Bensin = Manusia : ...',
                'a' => 'Makanan', 'b' => 'Air', 'c' => 'Oksigen',
                'd' => 'Vitamin', 'e' => 'Udara',
                'answer' => 'a',
                'explanation' => 'Mobil membutuhkan bensin sebagai bahan bakar, analoginya manusia membutuhkan makanan sebagai sumber energi.',
            ],
            [
                'question' => 'Berapa 25% dari 200?',
                'a' => '25', 'b' => '40', 'c' => '50', 'd' => '60', 'e' => '75',
                'answer' => 'c',
                'explanation' => '25% dari 200 = (25/100) x 200 = 50.',
            ],
            [
                'question' => 'Antonim dari kata "Aktif" adalah...',
                'a' => 'Giat', 'b' => 'Rajin', 'c' => 'Pasif',
                'd' => 'Produktif', 'e' => 'Dinamis',
                'answer' => 'c',
                'explanation' => 'Aktif berarti giat atau dinamis, antonimnya adalah pasif.',
            ],
            [
                'question' => '2, 3, 5, 7, 11, 13, ... Angka selanjutnya adalah...',
                'a' => '14', 'b' => '15', 'c' => '16', 'd' => '17', 'e' => '18',
                'answer' => 'd',
                'explanation' => 'Pola deret adalah bilangan prima: 2, 3, 5, 7, 11, 13, 17.',
            ],
            [
                'question' => 'Seorang pedagang membeli barang seharga Rp50.000 dan menjualnya dengan keuntungan 20%. Berapa harga jualnya?',
                'a' => 'Rp55.000', 'b' => 'Rp60.000', 'c' => 'Rp65.000',
                'd' => 'Rp70.000', 'e' => 'Rp75.000',
                'answer' => 'b',
                'explanation' => 'Keuntungan = 20% x Rp50.000 = Rp10.000. Harga jual = Rp50.000 + Rp10.000 = Rp60.000.',
            ],
            [
                'question' => 'Sinonim dari kata "Komprehensif" adalah...',
                'a' => 'Terbatas', 'b' => 'Menyeluruh', 'c' => 'Sebagian',
                'd' => 'Parsial', 'e' => 'Khusus',
                'answer' => 'b',
                'explanation' => 'Komprehensif berarti bersifat luas dan menyeluruh.',
            ],
            [
                'question' => 'Semua burung bisa terbang. Sebagian hewan di kandang adalah burung. Simpulan yang tepat adalah...',
                'a' => 'Semua hewan di kandang bisa terbang',
                'b' => 'Sebagian hewan di kandang bisa terbang',
                'c' => 'Semua yang bisa terbang adalah burung',
                'd' => 'Tidak ada hewan di kandang yang bisa terbang',
                'e' => 'Semua burung ada di kandang',
                'answer' => 'b',
                'explanation' => 'Karena semua burung bisa terbang dan sebagian hewan di kandang adalah burung, maka sebagian hewan di kandang bisa terbang.',
            ],
            [
                'question' => 'Antonim dari kata "Legal" adalah...',
                'a' => 'Halal', 'b' => 'Illegal', 'c' => 'Sah',
                'd' => 'Resmi', 'e' => 'Benar',
                'answer' => 'b',
                'explanation' => 'Legal berarti sah menurut hukum, antonimnya adalah ilegal (tidak sah).',
            ],
            [
                'question' => '1, 4, 9, 16, 25, ... Angka selanjutnya adalah...',
                'a' => '30', 'b' => '35', 'c' => '36', 'd' => '40', 'e' => '49',
                'answer' => 'c',
                'explanation' => 'Pola deret adalah kuadrat bilangan asli: 1²=1, 2²=4, 3²=9, 4²=16, 5²=25, 6²=36.',
            ],
            [
                'question' => 'Jika x + 5 = 12, maka x = ...',
                'a' => '5', 'b' => '6', 'c' => '7', 'd' => '8', 'e' => '9',
                'answer' => 'c',
                'explanation' => 'x + 5 = 12, maka x = 12 - 5 = 7.',
            ],
            [
                'question' => 'Sinonim dari kata "Prospek" adalah...',
                'a' => 'Masa depan', 'b' => 'Harapan', 'c' => 'Kemungkinan',
                'd' => 'Peluang', 'e' => 'Semua benar',
                'answer' => 'e',
                'explanation' => 'Prospek berarti harapan, kemungkinan, peluang, atau masa depan.',
            ],
            [
                'question' => 'Pesawat : Pilot = Bus : ...',
                'a' => 'Kondektur', 'b' => 'Supir', 'c' => 'Masinis',
                'd' => 'Nahkoda', 'e' => 'Kernet',
                'answer' => 'b',
                'explanation' => 'Pilot mengemudikan pesawat, analoginya supir mengemudikan bus.',
            ],
            [
                'question' => '100, 96, 92, 88, 84, ... Angka selanjutnya adalah...',
                'a' => '80', 'b' => '82', 'c' => '78', 'd' => '76', 'e' => '74',
                'answer' => 'a',
                'explanation' => 'Pola deret adalah pengurangan 4 setiap langkah, sehingga 84 - 4 = 80.',
            ],
            [
                'question' => 'Antonim dari kata "Mandiri" adalah...',
                'a' => 'Berdikari', 'b' => 'Bergantung', 'c' => 'Merdeka',
                'd' => 'Bebas', 'e' => 'Otonom',
                'answer' => 'b',
                'explanation' => 'Mandiri berarti tidak bergantung pada orang lain, antonimnya adalah bergantung.',
            ],
            [
                'question' => 'Sebuah persegi memiliki panjang sisi 8 cm. Berapa luasnya?',
                'a' => '16 cm²', 'b' => '32 cm²', 'c' => '48 cm²',
                'd' => '56 cm²', 'e' => '64 cm²',
                'answer' => 'e',
                'explanation' => 'Luas persegi = sisi x sisi = 8 x 8 = 64 cm².',
            ],
            [
                'question' => 'Sinonim dari kata "Ambiguitas" adalah...',
                'a' => 'Kejelasan', 'b' => 'Ketegasan', 'c' => 'Ketidakjelasan',
                'd' => 'Kepastian', 'e' => 'Ketentuan',
                'answer' => 'c',
                'explanation' => 'Ambiguitas berarti bermakna ganda atau tidak jelas, sinonimnya adalah ketidakjelasan.',
            ],
            [
                'question' => '2, 6, 18, 54, 162, ... Angka selanjutnya adalah...',
                'a' => '324', 'b' => '486', 'c' => '484', 'd' => '396', 'e' => '256',
                'answer' => 'b',
                'explanation' => 'Pola deret adalah perkalian 3, sehingga 162 x 3 = 486.',
            ],
            [
                'question' => 'Jika sebuah mobil menempuh jarak 120 km dalam 2 jam, berapa kecepatan rata-ratanya?',
                'a' => '40 km/jam', 'b' => '50 km/jam', 'c' => '60 km/jam',
                'd' => '70 km/jam', 'e' => '80 km/jam',
                'answer' => 'c',
                'explanation' => 'Kecepatan = jarak/waktu = 120 km / 2 jam = 60 km/jam.',
            ],
            [
                'question' => 'Dokter : Pasien = Guru : ...',
                'a' => 'Siswa', 'b' => 'Rumah sakit', 'c' => 'Sekolah',
                'd' => 'Kelas', 'e' => 'Buku',
                'answer' => 'a',
                'explanation' => 'Dokter menangani pasien, analoginya guru mengajar siswa.',
            ],
        ];

        foreach ($tiuQuestions as $q) {
            $order++;
            TryoutQuestion::create([
                'tryout_id' => $tryout->id,
                'order_number' => $order,
                'category' => 'tiu',
                'question_text' => $q['question'],
                'option_a' => $q['a'], 'option_b' => $q['b'],
                'option_c' => $q['c'], 'option_d' => $q['d'],
                'option_e' => $q['e'],
                'correct_answer' => $q['answer'],
                'explanation' => $q['explanation'],
            ]);
        }

        // ==================== TKP (45 SOAL) ====================
        $tkpQuestions = [
            [
                'question' => 'Anda baru saja diterima sebagai ASN. Sikap yang paling tepat adalah...',
                'a' => 'Langsung meminta jabatan tertentu kepada atasan',
                'b' => 'Mempelajari tugas dan tanggung jawab dengan sungguh-sungguh',
                'c' => 'Menunggu arahan atasan tanpa inisiatif',
                'd' => 'Bermalas-malasan karena status sudah tetap',
                'e' => 'Pindah ke instansi lain yang lebih baik',
                'scores' => [2, 5, 3, 1, 4],
                'explanation' => 'Sikap terbaik sebagai ASN baru adalah mempelajari tugas dengan sungguh-sungguh, menunjukkan profesionalisme dan tanggung jawab. Pindah instansi masih bisa diterima jika ada alasan kuat, namun malas dan diam tanpa inisiatif adalah sikap yang kurang tepat.',
            ],
            [
                'question' => 'Atasan memberikan tugas yang sangat sulit di luar kemampuan Anda. Sikap yang tepat...',
                'a' => 'Menolak tegas karena tidak mampu',
                'b' => 'Menerima dan berusaha belajar semaksimal mungkin',
                'c' => 'Meminta rekan lain mengerjakan tanpa sepengetahuan atasan',
                'd' => 'Mengabaikan tugas tersebut',
                'e' => 'Menerima tapi mengeluh pada semua rekan',
                'scores' => [2, 5, 3, 1, 4],
                'explanation' => 'Menerima tantangan dan berusaha belajar adalah sikap terbaik. Mengeluh itu wajar tapi tidak produktif, sedangkan mengabaikan tugas adalah pelanggaran.',
            ],
            [
                'question' => 'Rekan kerja melakukan pelanggaran ringan. Tindakan Anda...',
                'a' => 'Langsung melaporkan ke atasan',
                'b' => 'Menegur secara pribadi dengan baik dan sopan',
                'c' => 'Membiarkan saja karena bukan urusan saya',
                'd' => 'Ikut-ikutan melanggar',
                'e' => 'Menyebarkan berita ke rekan lain',
                'scores' => [4, 5, 3, 1, 2],
                'explanation' => 'Menegur langsung dengan cara baik adalah langkah paling tepat. Melapor ke atasan juga baik jika pelanggaran serius, namun untuk pelanggaran ringan teguran pribadi lebih utama.',
            ],
            [
                'question' => 'Seorang warga datang mengeluh dengan nada marah dan keras. Sikap Anda...',
                'a' => 'Menjawab dengan nada keras agar ia jera',
                'b' => 'Mendengarkan keluhan dengan sabar dan empati',
                'c' => 'Menyuruhnya pergi dan datang lagi besok',
                'd' => 'Mengabaikan dan pura-pura sibuk',
                'e' => 'Memanggil petugas keamanan untuk mengusir',
                'scores' => [2, 5, 4, 1, 3],
                'explanation' => 'Mendengarkan dengan sabar adalah sikap terbaik dalam pelayanan. Menyuruh datang lagi masih bisa diterima jika memang situasi tidak memungkinkan. Memanggil security harus menjadi pilihan terakhir.',
            ],
            [
                'question' => 'Instansi mengadakan program kerja bakti di hari libur. Sikap Anda...',
                'a' => 'Menolak karena hari libur adalah hak pribadi',
                'b' => 'Ikut berpartisipasi dengan sukarela',
                'c' => 'Ikut tapi tidak serius dan main-main',
                'd' => 'Tidak datang tanpa memberi kabar',
                'e' => 'Datang terlambat dan pulang lebih awal',
                'scores' => [2, 5, 4, 1, 3],
                'explanation' => 'Partisipasi sukarela menunjukkan dedikasi. Datang dan ikut meski tidak serius masih lebih baik dari tidak datang. Menolak mentah-mentah menunjukkan kurangnya kepedulian.',
            ],
            [
                'question' => 'Dalam rapat terjadi perbedaan pendapat yang cukup tajam. Sikap Anda...',
                'a' => 'Memaksakan pendapat sendiri karena paling benar',
                'b' => 'Menghargai pendapat lain dan mencari solusi terbaik bersama',
                'c' => 'Diam saja tidak mau berpendapat',
                'd' => 'Keluar dari ruang rapat',
                'e' => 'Mengikuti pendapat mayoritas tanpa pertimbangan',
                'scores' => [2, 5, 4, 1, 3],
                'explanation' => 'Menghargai pendapat orang lain dan musyawarah adalah sikap terbaik. Ikut mayoritas itu wajar, diam masih lebih baik dari marah atau keluar rapat.',
            ],
            [
                'question' => 'Instansi akan menerapkan sistem informasi baru. Sikap Anda...',
                'a' => 'Menolak karena sudah nyaman dengan sistem lama',
                'b' => 'Antusias mempelajari dan beradaptasi',
                'c' => 'Menunggu rekan yang lebih dulu belajar lalu meniru',
                'd' => 'Mengkritik terus tanpa mau belajar',
                'e' => 'Pura-pura sudah bisa padahal belum',
                'scores' => [2, 5, 4, 1, 3],
                'explanation' => 'Antusias belajar adalah adaptasi terbaik. Menunggu dan meniru rekan masih wajar dalam proses transisi. Pura-pura bisa berbahaya karena bisa menyebabkan kesalahan.',
            ],
            [
                'question' => 'Anda menemukan dompet berisi uang dan KTP di kantin kantor. Tindakan Anda...',
                'a' => 'Menyimpan uangnya dan membuang KTP',
                'b' => 'Menyerahkan ke bagian umum atau satpam',
                'c' => 'Mencari pemilik berdasarkan KTP lalu mengembalikan',
                'd' => 'Diam saja dan pura-pura tidak melihat',
                'e' => 'Mengambil uangnya lalu dompet dikembalikan',
                'scores' => [1, 4, 5, 2, 3],
                'explanation' => 'Mengembalikan langsung ke pemilik adalah tindakan paling terpuji. Menyerahkan ke petugas juga baik. Mengambil sebagian uang meski dompet dikembalikan tetap tidak jujur.',
            ],
            [
                'question' => 'Rekan kerja sedang sakit dan harus dirawat di rumah sakit. Sikap Anda...',
                'a' => 'Menjenguk dan menawarkan bantuan yang diperlukan',
                'b' => 'Mengabaikan karena bukan kerabat',
                'c' => 'Menanyakan kabar melalui rekan lain',
                'd' => 'Bergosip tentang penyakitnya dengan staf lain',
                'e' => 'Mengambil alih tugasnya tanpa koordinasi',
                'scores' => [5, 1, 4, 2, 3],
                'explanation' => 'Menjenguk langsung adalah kepedulian tertinggi. Menanyakan lewat orang lain masih wajar. Mengambil alih tugas tanpa koordinasi bisa menyebabkan masalah baru.',
            ],
            [
                'question' => 'Atasan memberikan kritik terhadap hasil kerja Anda. Sikap Anda...',
                'a' => 'Menerima dengan lapang dada dan memperbaiki',
                'b' => 'Marah dan tersinggung lalu membantah',
                'c' => 'Menerima kritik tapi tidak diindahkan',
                'd' => 'Menyalahkan faktor eksternal',
                'e' => 'Meminta maaf dan berjanji memperbaiki',
                'scores' => [5, 1, 3, 2, 4],
                'explanation' => 'Menerima kritik dan memperbaiki adalah sikap terbaik. Meminta maaf dan berjanji memperbaiki juga baik. Marah dan menyalahkan pihak lain menunjukkan kurangnya kedewasaan.',
            ],
            [
                'question' => 'Seorang warga meminta pelayanan yang tidak sesuai prosedur karena desakan waktu. Sikap Anda...',
                'a' => 'Melayani karena kasihan',
                'b' => 'Menjelaskan prosedur dengan sopan dan mencari solusi alternatif',
                'c' => 'Menyuruhnya pergi karena merepotkan',
                'd' => 'Menerima imbalan agar diproses',
                'e' => 'Mengabaikan permintaannya',
                'scores' => [3, 5, 2, 1, 4],
                'explanation' => 'Menjelaskan prosedur dan mencari solusi alternatif adalah pelayanan prima. Mengabaikan masih lebih baik dari menerima suap. Melayani di luar prosedur karena kasihan bisa berakibat masalah audit.',
            ],
            [
                'question' => 'Proyek tim yang Anda ketuai mengalami kegagalan. Sikap Anda...',
                'a' => 'Menyalahkan anggota tim sepihak',
                'b' => 'Mengakui kesalahan bersama dan mengevaluasi',
                'c' => 'Menyerah dan membubarkan tim',
                'd' => 'Pura-pura tidak tahu dan menghindar',
                'e' => 'Mengambil alih sendiri tanpa melibatkan anggota',
                'scores' => [2, 5, 3, 1, 4],
                'explanation' => 'Mengakui kesalahan bersama dan evaluasi adalah kepemimpinan sejati. Mengambil alih sendiri bisa menyelamatkan proyek namun mengabaikan kontribusi tim. Menyalahkan anggota tidak profesional.',
            ],
            [
                'question' => 'Anda memiliki ide inovatif yang bisa meningkatkan efisiensi kerja. Tindakan Anda...',
                'a' => 'Menyampaikan kepada atasan dengan data pendukung',
                'b' => 'Menyimpan ide untuk kepentingan pribadi',
                'c' => 'Menertawakan ide sendiri dan tidak jadi melaksanakan',
                'd' => 'Menunggu orang lain yang menyampaikan ide serupa',
                'e' => 'Langsung menerapkan tanpa izin atasan',
                'scores' => [5, 2, 3, 4, 1],
                'explanation' => 'Menyampaikan ke atasan dengan data adalah tindakan paling profesional. Menerapkan tanpa izin bisa melanggar prosedur. Menunggu orang lain menyampaikan menunjukkan kurang inisiatif.',
            ],
            [
                'question' => 'Bencana alam melanda daerah lain dan korban membutuhkan bantuan. Tindakan Anda...',
                'a' => 'Berpartisipasi dalam penggalangan dana dan bantuan',
                'b' => 'Masa bodoh karena lokasi jauh',
                'c' => 'Menunggu perintah atasan untuk bertindak',
                'd' => 'Menyebarkan berita palsu tentang bencana',
                'e' => 'Memanfaatkan situasi untuk mencari keuntungan',
                'scores' => [5, 1, 4, 2, 3],
                'explanation' => 'Berpartisipasi aktif dalam bantuan menunjukkan kepedulian sosial. Menunggu perintah masih wajar dalam birokrasi. Memanfaatkan bencana untuk keuntungan pribadi sangat tercela.',
            ],
            [
                'question' => 'Atasan meminta pendapat tentang suatu kebijakan baru. Anda belum yakin. Sikap Anda...',
                'a' => 'Mengatakan tidak tahu dan tidak memberi pendapat',
                'b' => 'Memberikan pendapat berdasarkan data yang ada meskipun terbatas',
                'c' => 'Diam saja pura-pura tidak mendengar',
                'd' => 'Membuat alasan menghindar',
                'e' => 'Berbohong mengatakan yakin padahal tidak',
                'scores' => [3, 5, 2, 4, 1],
                'explanation' => 'Memberikan pendapat berdasarkan data yang ada adalah sikap paling bertanggung jawab. Membuat alasan masih lebih baik dari berbohong. Berbohong tentang keyakinan bisa berakibat fatal.',
            ],
            [
                'question' => 'Dua rekan kerja terlibat konflik dan saling menjelekkan. Sikap Anda...',
                'a' => 'Memihak salah satu yang Anda kenal dekat',
                'b' => 'Mendamaikan dan menjadi mediator yang netral',
                'c' => 'Membiarkan karena bukan urusan Anda',
                'd' => 'Menghasut mereka agar konflik semakin besar',
                'e' => 'Melaporkan keduanya ke atasan tanpa mediasi',
                'scores' => [2, 5, 4, 1, 3],
                'explanation' => 'Menjadi mediator netral adalah yang terbaik. Melapor ke atasan juga bisa diterima jika konflik sudah parah. Memihak dan menghasut hanya akan memperburuk situasi.',
            ],
            [
                'question' => 'Atasan menawarkan promosi jabatan yang membutuhkan tanggung jawab besar. Sikap Anda...',
                'a' => 'Menerima dengan penuh kesiapan dan komitmen',
                'b' => 'Menolak karena takut gagal',
                'c' => 'Menerima tapi tidak serius menjalankan',
                'd' => 'Meminta orang lain untuk menggantikan',
                'e' => 'Menerima dengan syarat tertentu',
                'scores' => [5, 2, 1, 3, 4],
                'explanation' => 'Menerima dengan kesiapan penuh adalah sikap terbaik. Menerima dengan syarat masih wajar dalam negosiasi. Menolak karena takut wajar tapi menghambat pengembangan karir.',
            ],
            [
                'question' => 'Anggaran instansi mengalami pemotongan signifikan. Sikap Anda sebagai pimpinan...',
                'a' => 'Menggunakan dana pribadi untuk kebutuhan dinas',
                'b' => 'Mengusulkan program efisiensi dan skala prioritas',
                'c' => 'Diam saja dan menerima apa adanya',
                'd' => 'Memotong anggaran secara sepihak',
                'e' => 'Mencari pinjaman ke pihak ketiga',
                'scores' => [3, 5, 2, 4, 1],
                'explanation' => 'Mengusulkan efisiensi adalah solusi terbaik dan sesuai prosedur. Memotong sepihak berisiko. Mencari pinjaman ke pihak ketiga berbahaya dan melanggar aturan keuangan negara.',
            ],
            [
                'question' => 'Warga menyampaikan ketidakpuasan terhadap pelayanan instansi Anda. Sikap Anda...',
                'a' => 'Meminta maaf dan berjanji memperbaiki pelayanan',
                'b' => 'Membela diri dan menyalahkan warga',
                'c' => 'Menjelaskan keterbatasan yang ada',
                'd' => 'Mengabaikan keluhan',
                'e' => 'Melaporkan warga pada atasan karena dianggap mencemarkan',
                'scores' => [5, 1, 4, 2, 3],
                'explanation' => 'Meminta maaf dan memperbaiki adalah sikap terbaik. Menjelaskan keterbatasan juga baik sebagai bentuk transparansi. Membela diri dan menyalahkan warga tidak profesional.',
            ],
            [
                'question' => 'Anda mendapat kesempatan mengikuti pelatihan di luar kota. Sikap Anda...',
                'a' => 'Antusias mengikuti dan menerapkan ilmunya',
                'b' => 'Malas karena merepotkan dan mengganggu waktu istirahat',
                'c' => 'Ikut tapi tidak serius karena tidak diminati',
                'd' => 'Menolak dengan alasan sibuk padahal tidak',
                'e' => 'Mengikuti pelatihan untuk jalan-jalan',
                'scores' => [5, 2, 4, 1, 3],
                'explanation' => 'Antusias dan menerapkan ilmu adalah sikap pengembangan diri terbaik. Ikut tidak serius masih lebih baik dari menolak. Mengikuti untuk jalan-jalan tidak sesuai tujuan pelatihan.',
            ],
            [
                'question' => 'Rekan kerja mendapatkan penghargaan atas prestasinya. Sikap Anda...',
                'a' => 'Turut bangga dan termotivasi untuk berprestasi',
                'b' => 'Iri dan meremehkan pencapaiannya',
                'c' => 'Biasa saja dan tidak peduli',
                'd' => 'Menyebarkan isu bahwa ia curang',
                'e' => 'Mengucapkan selamat dan meminta tips sukses',
                'scores' => [5, 1, 3, 2, 4],
                'explanation' => 'Mengucapkan selamat dan termotivasi adalah sikap positif. Biasa saja wajar namun kurang mendukung. Iri dan menyebarkan isu negatif menunjukkan mentalitas tidak sehat.',
            ],
            [
                'question' => 'Anda memiliki beberapa pekerjaan dengan tenggat waktu yang sama. Sikap Anda...',
                'a' => 'Membuat skala prioritas dan menyelesaikan bertahap',
                'b' => 'Panik dan stres tidak bisa bekerja optimal',
                'c' => 'Mengerjakan asal selesai tanpa memperhatikan kualitas',
                'd' => 'Menunda semua pekerjaan',
                'e' => 'Meminta perpanjangan semua tenggat waktu',
                'scores' => [5, 3, 4, 1, 2],
                'explanation' => 'Membuat prioritas dan bekerja bertahap adalah manajemen kerja terbaik. Meminta perpanjangan untuk tugas prioritas masih wajar. Menunda semua pekerjaan adalah yang terburuk.',
            ],
            [
                'question' => 'Rekan kerja kewalahan menangani tugas dan meminta bantuan. Anda juga sibuk. Sikap Anda...',
                'a' => 'Membantu semampu tanpa mengabaikan tugas sendiri',
                'b' => 'Menolak mentah-mentah karena sibuk',
                'c' => 'Membantu setengah hati dan sambil mengeluh',
                'd' => 'Pura-pura sibuk agar tidak dimintai bantuan',
                'e' => 'Menyuruhnya minta tolong ke orang lain',
                'scores' => [5, 2, 4, 1, 3],
                'explanation' => 'Membantu semampu mungkin adalah sikap gotong royong. Menolak dengan sopan masih lebih baik dari pura-pura sibuk. Membantu setengah hati lebih baik dari menolak sama sekali.',
            ],
            [
                'question' => 'Ada kebijakan baru yang menurut Anda kurang tepat untuk diterapkan. Sikap Anda...',
                'a' => 'Menyampaikan masukan dan alternatif secara konstruktif',
                'b' => 'Menolak dan tidak melaksanakan kebijakan',
                'c' => 'Mengomentari negatif di media sosial',
                'd' => 'Diam dan tidak peduli tapi tidak menjalankan',
                'e' => 'Melaksanakan kebijakan sambil memprotes terus',
                'scores' => [5, 2, 1, 3, 4],
                'explanation' => 'Masukan konstruktif adalah bentuk kepedulian terbaik. Melaksanakan sambil menyampaikan keberatan masih wajar. Mengomentari negatif di publik tidak profesional dan melanggar kode etik.',
            ],
            [
                'question' => 'Di perjalanan Anda melihat kecelakaan lalu lintas. Tindakan Anda...',
                'a' => 'Berhenti dan memberikan pertolongan seperlunya',
                'b' => 'Mengabaikan karena takut terlibat masalah',
                'c' => 'Menonton dari kejauhan',
                'd' => 'Mengambil video untuk diunggah ke media sosial',
                'e' => 'Menghubungi pihak berwenang lalu pergi',
                'scores' => [5, 2, 3, 1, 4],
                'explanation' => 'Menolong langsung dan menghubungi pihak berwenang adalah tindakan terpuji. Menghubungi pihak berwenang lalu pergi masih membantu. Mengambil video tanpa menolong adalah tindakan tidak peduli.',
            ],
            [
                'question' => 'Anda menjadi ketua tim. Anggota tim memiliki latar belakang dan kemampuan berbeda. Sikap Anda...',
                'a' => 'Menghargai perbedaan dan membagi tugas sesuai kompetensi',
                'b' => 'Memerintah dengan otoriter',
                'c' => 'Mengerjakan semua sendiri karena tidak percaya anggota',
                'd' => 'Membeda-bedakan anggota berdasarkan kedekatan',
                'e' => 'Memberi tugas asal tanpa melihat kemampuan',
                'scores' => [5, 2, 4, 1, 3],
                'explanation' => 'Menghargai perbedaan dan membagi tugas sesuai kompetensi adalah kepemimpinan ideal. Mengerjakan sendiri menunjukkan kurangnya kepercayaan pada tim. Membeda-bedakan anggota tidak adil.',
            ],
            [
                'question' => 'Anda melakukan kesalahan dalam pelaporan data ke atasan. Sikap Anda...',
                'a' => 'Mengakui kesalahan dan segera memperbaiki laporan',
                'b' => 'Menyalahkan staf atau rekan yang memberi data',
                'c' => 'Menutup-nutupi kesalahan',
                'd' => 'Pura-pura tidak terjadi apa-apa',
                'e' => 'Mengoreksi diam-diam tanpa memberi tahu atasan',
                'scores' => [5, 1, 2, 3, 4],
                'explanation' => 'Mengakui dan memperbaiki adalah integritas tertinggi. Mengoreksi diam-diam masih bisa diterima jika tidak berdampak besar. Menutup-nutupi hanya akan memperburuk masalah.',
            ],
            [
                'question' => 'Rapat berlangsung sangat lama dan mulai tidak efektif. Sikap Anda...',
                'a' => 'Tetap fokus dan berpartisipasi aktif',
                'b' => 'Tidur-tiduran di kursi',
                'c' => 'Main handphone saat rapat',
                'd' => 'Keluar masuk ruangan berkali-kali',
                'e' => 'Mengusulkan agar rapat diskors atau dilanjutkan lain waktu',
                'scores' => [5, 1, 2, 3, 4],
                'explanation' => 'Tetap fokus adalah sikap paling profesional. Mengusulkan skor menunjukkan inisiatif memperbaiki efektivitas rapat. Main handphone atau tidur tidak sopan.',
            ],
            [
                'question' => 'Warga lanjut usia (lansia) yang buta huruf datang mengurus dokumen kependudukan. Sikap Anda...',
                'a' => 'Membantu dengan sabar dan menjelaskan dengan bahasa sederhana',
                'b' => 'Menyuruhnya pulang dan datang lagi dengan pendamping',
                'c' => 'Berkata keras karena ia tidak mengerti prosedur',
                'd' => 'Mengabaikan dan melayani pengunjung lain',
                'e' => 'Menyuruh ke loket lain tanpa menjelaskan',
                'scores' => [5, 4, 1, 2, 3],
                'explanation' => 'Membantu dengan sabar adalah pelayanan prima. Menyuruh datang dengan pendamping masih wajar jika situasi tidak memungkinkan. Berkata kasar sangat tidak profesional.',
            ],
            [
                'question' => 'Warga yang Anda bantu menawarkan hadiah sebagai ucapan terima kasih. Sikap Anda...',
                'a' => 'Menolak dengan sopan karena itu sudah kewajiban',
                'b' => 'Menerima karena sudah membantu',
                'c' => 'Meminta lebih karena jasanya besar',
                'd' => 'Menerima dan melaporkan ke atasan',
                'e' => 'Menerima dengan syarat tidak memberi tahu siapa pun',
                'scores' => [5, 2, 1, 4, 3],
                'explanation' => 'Menolak dengan sopan adalah sikap paling berintegritas. Menerima dan melaporkan masih transparan dan bisa diterima dalam budaya tertentu. Meminta imbalan adalah pelanggaran etik berat.',
            ],
            [
                'question' => 'Atasan meminta Anda memberikan sanksi pada rekan yang melanggar aturan. Sikap Anda...',
                'a' => 'Memberikan sanksi sesuai aturan dan prosedur yang berlaku',
                'b' => 'Membiarkan karena teman dekat',
                'c' => 'Memberikan sanksi ringan sebagai formalitas',
                'd' => 'Melaporkan ke instansi yang lebih berwenang',
                'e' => 'Memberi peringatan lisan tanpa sanksi tertulis',
                'scores' => [5, 1, 3, 4, 2],
                'explanation' => 'Sanksi sesuai aturan adalah keadilan sejati. Melapor ke instansi berwenang juga tepat jika pelanggaran serius. Memberi sanksi ringan sebagai formalitas tidak menjamin efek jera.',
            ],
            [
                'question' => 'Instansi kedatangan tamu penting dari kementerian. Sikap Anda...',
                'a' => 'Menyambut dengan ramah dan profesional',
                'b' => 'Acuh tak acuh karena bukan urusan saya',
                'c' => 'Pura-pura sibuk agar tidak diminta membantu',
                'd' => 'Menyuruh rekan lain menyambut',
                'e' => 'Bersikap berlebihan dan menjilat',
                'scores' => [5, 2, 3, 4, 1],
                'explanation' => 'Menyambut ramah dan profesional adalah sikap tepat. Menyuruh rekan lain juga bisa diterima jika Anda ada tugas prioritas. Bersikap berlebihan dan menjilat justru tidak profesional.',
            ],
            [
                'question' => 'Anda menemukan dokumen rahasia instansi tertinggal di mesin fotokopi. Tindakan Anda...',
                'a' => 'Mengamankan dan mengembalikan ke bagian terkait',
                'b' => 'Membiarkan saja',
                'c' => 'Membaca isi dokumen karena penasaran',
                'd' => 'Membuang ke tempat sampah',
                'e' => 'Menyebarkan ke grup WhatsApp',
                'scores' => [5, 3, 4, 2, 1],
                'explanation' => 'Mengamankan dan mengembalikan adalah paling bertanggung jawab. Membaca karena penasaran masih wajar tapi tidak profesional. Menyebarkan dokumen rahasia adalah pelanggaran berat.',
            ],
            [
                'question' => 'Anda memiliki perbedaan prinsip yang mendasar dengan atasan. Sikap Anda...',
                'a' => 'Menyampaikan pendapat dengan sopan dan argumen logis',
                'b' => 'Langsung menyetujui semua pendapat atasan',
                'c' => 'Membantah dengan keras',
                'd' => 'Diam tapi tidak setuju dan tidak menjalankan',
                'e' => 'Mencari dukungan rekan untuk melawan atasan',
                'scores' => [5, 3, 2, 4, 1],
                'explanation' => 'Menyampaikan pendapat dengan sopan adalah komunikasi asertif terbaik. Diam tapi tetap menjalankan tugas masih bisa diterima. Mencari dukungan untuk melawan atasan tidak profesional.',
            ],
            [
                'question' => 'Program kerja yang Anda rencanakan tidak mencapai target. Sikap Anda...',
                'a' => 'Mengevaluasi penyebab dan menyusun strategi baru',
                'b' => 'Menyalahkan faktor eksternal',
                'c' => 'Pasrah dan tidak melakukan perbaikan',
                'd' => 'Mengusulkan program baru tanpa evaluasi',
                'e' => 'Menyerah dan mengundurkan diri dari tanggung jawab',
                'scores' => [5, 2, 3, 4, 1],
                'explanation' => 'Evaluasi dan strategi baru adalah paling profesional. Mengusulkan program baru tanpa evaluasi berisiko gagal lagi. Menyerah adalah sikap paling tidak bertanggung jawab.',
            ],
            [
                'question' => 'Ada lowongan promosi jabatan yang sesuai kualifikasi Anda. Sikap Anda...',
                'a' => 'Mendaftar secara resmi dan mempersiapkan diri',
                'b' => 'Tidak peduli karena merasa tidak mampu',
                'c' => 'Menyebarkan isu negatif tentang pesaing',
                'd' => 'Pasrah dan tidak melakukan apa-apa',
                'e' => 'Meminta atasan langsung menunjuk tanpa seleksi',
                'scores' => [5, 2, 1, 3, 4],
                'explanation' => 'Mendaftar resmi adalah sikap profesional. Meminta ditunjuk langsung bisa dianggap tidak fair. Isu negatif tentang pesaing adalah kecurangan dan tidak etis.',
            ],
            [
                'question' => 'Rekan kerja sering meminjam uang tapi tidak mengembalikan. Sikap Anda...',
                'a' => 'Menegur dengan baik dan mengingatkan',
                'b' => 'Meminjamkan lagi agar ia malu',
                'c' => 'Menggunjing di belakang',
                'd' => 'Melaporkan ke atasan',
                'e' => 'Memutuskan hubungan pertemanan',
                'scores' => [5, 2, 3, 4, 1],
                'explanation' => 'Menegur langsung adalah langkah dewasa dan tepat. Melapor ke atasan bisa ditempuh jika sudah berulang. Memutuskan pertemanan tanpa komunikasi adalah langkah paling ekstrem.',
            ],
            [
                'question' => 'Anda ditugaskan di daerah terpencil dan tertinggal. Sikap Anda...',
                'a' => 'Menerima sebagai tantangan dan bentuk pengabdian',
                'b' => 'Menolak keras dan memprotes keputusan',
                'c' => 'Menerima tapi mengeluh setiap saat',
                'd' => 'Mencari alasan medis untuk tidak berangkat',
                'e' => 'Mengajukan mutasi ke instansi lain',
                'scores' => [5, 1, 3, 2, 4],
                'explanation' => 'Menerima sebagai pengabdian adalah sikap terpuji. Mengajukan mutasi masih wajar jika ada alasan kuat. Menolak keras tanpa alasan jelas menunjukkan kurang dedikasi.',
            ],
            [
                'question' => 'Beredar berita hoax yang mencemarkan nama baik instansi Anda. Tindakan Anda...',
                'a' => 'Meluruskan informasi dengan data dan fakta yang benar',
                'b' => 'Menyebarkan berita tersebut tanpa verifikasi',
                'c' => 'Mengabaikan karena tidak berdampak langsung',
                'd' => 'Menambah-nambahi informasi agar lebih viral',
                'e' => 'Marah dan berkomentar emosional di media sosial',
                'scores' => [5, 1, 3, 2, 4],
                'explanation' => 'Meluruskan informasi dengan data adalah tindakan paling bertanggung jawab. Marah dan berkomentar emosional bisa memperkeruh situasi. Ikut menyebarkan hoax sangat tidak profesional.',
            ],
            [
                'question' => 'Anda kehilangan dokumen penting instansi karena kelalaian. Tindakan Anda...',
                'a' => 'Melaporkan ke atasan dan mencari solusi bersama',
                'b' => 'Diam dan berharap tidak diketahui',
                'c' => 'Memalsukan dokumen pengganti',
                'd' => 'Menyalahkan rekan yang meminjam terakhir',
                'e' => 'Mencari sendiri diam-diam tanpa lapor',
                'scores' => [5, 2, 1, 3, 4],
                'explanation' => 'Melapor dan mencari solusi adalah sikap bertanggung jawab. Mencari sendiri tanpa lapor masih bisa diterima. Memalsukan dokumen adalah tindak pidana yang sangat serius.',
            ],
            [
                'question' => 'Warga mengusulkan ide pembangunan infrastruktur di lingkungannya. Sikap Anda...',
                'a' => 'Menampung usulan dan mempelajari kelayakannya',
                'b' => 'Menolak langsung karena tidak sesuai program',
                'c' => 'Mengabaikan usulan',
                'd' => 'Mengejek usulan karena dianggap tidak realistis',
                'e' => 'Mengklaim usulan sebagai ide sendiri',
                'scores' => [5, 3, 2, 1, 4],
                'explanation' => 'Menampung dan mempelajari usulan adalah pelayanan partisipatif. Menolak dengan alasan jelas masih lebih baik dari mengabaikan. Mengklaim ide warga sebagai milik sendiri tidak etis.',
            ],
            [
                'question' => 'Anda memiliki hobi fotografi yang bisa mendukung humas instansi. Sikap Anda...',
                'a' => 'Mengembangkan hobi untuk menunjang dokumentasi instansi',
                'b' => 'Mengabaikan karena bukan tugas pokok',
                'c' => 'Hanya fokus pada hobi dan melalaikan tugas utama',
                'd' => 'Menyembunyikan hobi karena takut dieksploitasi',
                'e' => 'Mengomersialkan hobi saat jam kerja',
                'scores' => [5, 3, 1, 2, 4],
                'explanation' => 'Mengembangkan hobi untuk kepentingan instansi adalah sinergi sempurna. Menyembunyikan hobi karena khawatir masih wajar. Mengomersialkan saat jam kerja melanggar aturan.',
            ],
            [
                'question' => 'Atasan meminta melakukan tugas yang bertentangan dengan hati nurani dan kode etik. Sikap Anda...',
                'a' => 'Menolak dengan sopan dan menjelaskan dasar keberatan',
                'b' => 'Melakukan karena takut dianggap pembangkang',
                'c' => 'Melakukan tapi mengeluh pada rekan',
                'd' => 'Diam dan tidak melaksanakan tanpa penjelasan',
                'e' => 'Menyebarkan ke media sosial',
                'scores' => [5, 2, 3, 4, 1],
                'explanation' => 'Menolak dengan sopan dan argumen jelas adalah integritas tertinggi. Diam tanpa melaksanakan bisa disalahartikan. Menyebarkan ke media sosial melanggar etika dan aturan.',
            ],
            [
                'question' => 'Rekan baru mengalami kesulitan beradaptasi dengan lingkungan kerja. Sikap Anda...',
                'a' => 'Membantu membimbing dan memberi arahan dengan sabar',
                'b' => 'Membiarkan belajar sendiri',
                'c' => 'Menertawakan ketidakmampuannya',
                'd' => 'Memberi tugas berat untuk menguji kemampuannya',
                'e' => 'Mengabaikan dan tidak mau diganggu',
                'scores' => [5, 3, 1, 2, 4],
                'explanation' => 'Membimbing dengan sabar adalah sikap terbaik. Memberi tugas berat untuk menguji bisa jadi strategi pengembangan. Menertawakan ketidakmampuan rekan sangat tidak profesional.',
            ],
            [
                'question' => 'Instansi Anda meraih penghargaan tingkat nasional. Sikap Anda...',
                'a' => 'Turut bangga dan berkomitmen mempertahankan prestasi',
                'b' => 'Biasa saja karena bukan prestasi pribadi',
                'c' => 'Merasa kurang karena target belum semua tercapai',
                'd' => 'Iri pada instansi lain yang meraih lebih banyak',
                'e' => 'Tidak peduli karena tidak terlibat langsung',
                'scores' => [5, 3, 4, 1, 2],
                'explanation' => 'Bangga dan mempertahankan prestasi adalah sikap positif. Merasa kurang dan ingin lebih baik juga baik untuk perbaikan. Iri pada instansi lain tidak produktif.',
            ],
        ];

        foreach ($tkpQuestions as $q) {
            $order++;
            TryoutQuestion::create([
                'tryout_id' => $tryout->id,
                'order_number' => $order,
                'category' => 'tkp',
                'question_text' => $q['question'],
                'option_a' => $q['a'], 'option_b' => $q['b'],
                'option_c' => $q['c'], 'option_d' => $q['d'],
                'option_e' => $q['e'],
                'correct_answer' => null,
                'score_a' => $q['scores'][0], 'score_b' => $q['scores'][1],
                'score_c' => $q['scores'][2], 'score_d' => $q['scores'][3],
                'score_e' => $q['scores'][4],
                'explanation' => $q['explanation'],
            ]);
        }

        $this->command->info("Try Out berhasil dibuat: {$tryout->name}");
        $this->command->info("TWK: 30 soal, TIU: 35 soal, TKP: 45 soal = {$order} soal");
    }
}
