<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use ZipArchive;

class BackupController extends Controller
{
    // Halaman backup
    public function index()
    {
        $backupFiles = [];
        $backupDir = storage_path('app/backups');
        
        if (File::exists($backupDir)) {
            $files = File::files($backupDir);
            foreach ($files as $file) {
                $backupFiles[] = [
                    'name' => $file->getFilename(),
                    'size' => $this->formatSize($file->getSize()),
                    'date' => date('d/m/Y H:i:s', $file->getMTime()),
                    'path' => $file->getPathname()
                ];
            }
            $backupFiles = array_reverse($backupFiles);
        }
        
        return view('admin.backup.index', compact('backupFiles'));
    }
    
    // Membuat backup (database + file gambar)
    public function backup()
    {
        try {
            $backupDir = storage_path('app/backups');
            if (!File::exists($backupDir)) {
                File::makeDirectory($backupDir, 0777, true);
            }
            
            // Nama folder backup
            $backupFolderName = 'backup_' . date('Y-m-d_H-i-s');
            $backupFolderPath = $backupDir . '/' . $backupFolderName;
            
            // Buat folder backup
            if (!File::exists($backupFolderPath)) {
                File::makeDirectory($backupFolderPath, 0777, true);
            }
            
            // 1. Backup database ke file SQL
            $sqlFilename = 'database.sql';
            $sqlFilepath = $backupFolderPath . '/' . $sqlFilename;
            $this->backupManual($sqlFilepath);
            
            // 2. Backup file gambar
            $imagesSource = public_path('uploads');
            $imagesDest = $backupFolderPath . '/uploads';
            
            if (File::exists($imagesSource)) {
                File::copyDirectory($imagesSource, $imagesDest);
            }
            
            // 3. Buat file zip
            $zipFilename = $backupFolderName . '.zip';
            $zipFilepath = $backupDir . '/' . $zipFilename;
            
            $zip = new ZipArchive();
            if ($zip->open($zipFilepath, ZipArchive::CREATE) === TRUE) {
                $this->addFolderToZip($backupFolderPath, $zip, $backupFolderName);
                $zip->close();
            }
            
            // 4. Hapus folder temporary
            File::deleteDirectory($backupFolderPath);
            
            // 5. Hapus backup lama (lebih dari 30 hari)
            $this->deleteOldBackups($backupDir, 30);
            
            if (File::exists($zipFilepath) && File::size($zipFilepath) > 0) {
                return response()->json([
                    'success' => true,
                    'message' => 'Backup berhasil dibuat! File zip: ' . $zipFilename,
                    'filename' => $zipFilename
                ]);
            } else {
                throw new \Exception('Gagal membuat backup zip');
            }
            
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Backup gagal: ' . $e->getMessage()
            ], 500);
        }
    }
    
    // Menambahkan folder ke zip
    private function addFolderToZip($source, $zip, $folderName)
    {
        $files = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($source),
            \RecursiveIteratorIterator::LEAVES_ONLY
        );
        
        foreach ($files as $file) {
            if (!$file->isDir()) {
                $filePath = $file->getRealPath();
                $relativePath = substr($filePath, strlen($source) + 1);
                $zip->addFile($filePath, $folderName . '/' . $relativePath);
            }
        }
    }
    
    // Backup manual database
    private function backupManual($filepath)
    {
        $tables = DB::select('SHOW TABLES');
        $dbName = env('DB_DATABASE', 'belajar_cpns');
        $tableKey = "Tables_in_{$dbName}";
        
        $sql = "-- Backup Database: {$dbName}\n";
        $sql .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
        $sql .= "-- Generated by: Belajar CPNS\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
        
        foreach ($tables as $table) {
            $tableName = $table->$tableKey;
            
            $sql .= "DROP TABLE IF EXISTS `{$tableName}`;\n";
            
            $createTable = DB::select("SHOW CREATE TABLE {$tableName}");
            $sql .= $createTable[0]->{'Create Table'} . ";\n\n";
            
            $data = DB::table($tableName)->get();
            if (count($data) > 0) {
                foreach ($data as $row) {
                    $columns = [];
                    $values = [];
                    foreach ((array)$row as $key => $value) {
                        $columns[] = "`{$key}`";
                        $values[] = is_null($value) ? 'NULL' : "'" . addslashes($value) . "'";
                    }
                    $sql .= "INSERT INTO `{$tableName}` (" . implode(', ', $columns) . ") VALUES (" . implode(', ', $values) . ");\n";
                }
                $sql .= "\n";
            }
        }
        
        $sql .= "\nSET FOREIGN_KEY_CHECKS=1;\n";
        
        File::put($filepath, $sql);
    }
    
    // Hapus backup lama
    private function deleteOldBackups($backupDir, $daysOld)
    {
        $files = File::files($backupDir);
        $now = time();
        
        foreach ($files as $file) {
            if ($file->getExtension() == 'zip') {
                $fileAge = $now - $file->getMTime();
                $days = $fileAge / (60 * 60 * 24);
                if ($days > $daysOld) {
                    File::delete($file->getPathname());
                }
            }
        }
    }
    
    // Download backup
    public function download($filename)
    {
        $filepath = storage_path('app/backups/' . $filename);
        
        if (!File::exists($filepath)) {
            return redirect()->back()->with('error', 'File backup tidak ditemukan!');
        }
        
        return response()->download($filepath, $filename, [
            'Content-Type' => 'application/zip'
        ]);
    }
    
    // Hapus backup
    public function delete($filename)
    {
        $filepath = storage_path('app/backups/' . $filename);
        
        if (File::exists($filepath)) {
            File::delete($filepath);
            return response()->json(['success' => true, 'message' => 'Backup berhasil dihapus!']);
        }
        
        return response()->json(['success' => false, 'message' => 'File tidak ditemukan!'], 404);
    }
    
    // Restore database dari file zip
    public function restore(Request $request)
    {
        $request->validate([
            'backup_file' => 'required|file|mimes:zip|max:51200'
        ]);
        
        try {
            $file = $request->file('backup_file');
            $zip = new ZipArchive();
            $tempDir = storage_path('app/backups/temp_' . time());
            
            // Buat folder temporary
            if (!File::exists($tempDir)) {
                File::makeDirectory($tempDir, 0777, true);
            }
            
            // Extract zip
            $zip->open($file->getPathname());
            $zip->extractTo($tempDir);
            $zip->close();
            
            // Cari file database.sql dan folder uploads
            $sqlFile = null;
            $uploadDir = null;
            
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($tempDir),
                \RecursiveIteratorIterator::SELF_FIRST
            );
            
            foreach ($iterator as $item) {
                if ($item->isFile()) {
                    if ($item->getFilename() == 'database.sql') {
                        $sqlFile = $item->getRealPath();
                    }
                }
                if ($item->isDir() && $item->getFilename() == 'uploads') {
                    $uploadDir = $item->getRealPath();
                }
            }
            
            // Restore database
            if ($sqlFile && file_exists($sqlFile)) {
                $content = file_get_contents($sqlFile);
                $content = str_replace('SET FOREIGN_KEY_CHECKS=0;', '', $content);
                $content = str_replace('SET FOREIGN_KEY_CHECKS=1;', '', $content);
                $queries = explode(";\n", $content);
                
                DB::statement('SET FOREIGN_KEY_CHECKS=0');
                foreach ($queries as $query) {
                    $query = trim($query);
                    if (!empty($query) && $query != '') {
                        try {
                            DB::statement($query);
                        } catch (\Exception $e) {
                            // Abaikan error minor
                        }
                    }
                }
                DB::statement('SET FOREIGN_KEY_CHECKS=1');
            }
            
            // Restore file gambar
            if ($uploadDir && is_dir($uploadDir)) {
                // Backup gambar lama (optional)
                $oldUploadsBackup = public_path('uploads_backup_' . time());
                if (File::exists(public_path('uploads'))) {
                    File::copyDirectory(public_path('uploads'), $oldUploadsBackup);
                }
                
                // Hapus folder uploads lama
                if (File::exists(public_path('uploads'))) {
                    File::deleteDirectory(public_path('uploads'));
                }
                
                // Buat folder uploads baru
                File::makeDirectory(public_path('uploads'), 0777, true);
                File::makeDirectory(public_path('uploads/materi'), 0777, true);
                File::makeDirectory(public_path('uploads/tryouts'), 0777, true);
                
                // Copy gambar baru
                File::copyDirectory($uploadDir, public_path('uploads'));
            }
            
            // Hapus folder temporary
            File::deleteDirectory($tempDir);
            
            return redirect()->route('admin.backup.index')->with('success', 'Restore berhasil! Database dan gambar telah dikembalikan.');
            
        } catch (\Exception $e) {
            return redirect()->back()->with('error', 'Restore gagal: ' . $e->getMessage());
        }
    }
    
    private function formatSize($bytes)
    {
        if ($bytes >= 1048576) {
            return round($bytes / 1048576, 2) . ' MB';
        } elseif ($bytes >= 1024) {
            return round($bytes / 1024, 2) . ' KB';
        } else {
            return $bytes . ' B';
        }
    }
}